// Generated by typings
// Source: https://raw.githubusercontent.com/typed-typings/npm-pinkie-promise/master/index.d.ts
declare module 'pinkie-promise' {
import { Promise } from 'es6-promise';

export = Promise;
}
