// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/master/replace-ext/replace-ext.d.ts
declare function replaceExt(npath: string, ext: string): string;

declare module 'replace-ext' {
    export = replaceExt;
}
